language: python
python:
    - "3.0"
    - "3.1"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"



before_install:
    - pip install -r requirements.txt

install:
    python setup.py install

notifications:
    email:
        akash.p1997@gmail.com
